### ISSUE TITLE
The native messaging opens but it doesn't work

### ISSUE THREAD

**Issue by umidoo** [pendo324/EssentialNowPlaying#29]
Trying to use WebApps to get Pandora songs and everything is fine. It says pandora is supported on the chrome extension and opens the native messaging interface, but the Essential Now Playing.exe still shows "Pandora not open." what do I do?

**Comment by IranEG** [comment]
Hey,
To use the WebApps you need to do the following:
1. Open Essential Now Playing.
2. Select the Player and set the file path.
3. Head to Pandora or any other web player.
4. Click on the Now Playing Companion Extension and "Use on this page".
(You should see the NativeMessagingInterface background process start up in Task Manager)
5. On the web pop-up click "Start".
6. Go back to Essential Now Playing app and hit "Start!".

The issue seems to be that you must have EssentialNowPlaying.exe running before you enable the Playing Companion Extension in order for the NativeMessagingInterface to load properly.

After NativeMessagingInterface has been loaded you can go ahead and change WebApps (Spotify, SoundCloud, etc.) without any issues since the problem was initializing NativeMessagingInterface.
