### ISSUE TITLE
Spotify web not working

### ISSUE THREAD

**Issue by lolcamp95** [pendo324/EssentialNowPlaying#35]
Heya!
I have gotten Soundcloud and other ones to work, but the Spotify web player that I want to use, doesn't work.. The start and stop button comes up, but it says that it's not supported

 I have tried to google it up, but can't find any solution. 

All help and suggestions are appreciated!

**Comment by pendo324** [comment]
I'm on vacation at the moment but I'll take a look at it when I get a chance. One of the other contributors might be able to pick this up before I get a chance

**Comment by IranEG** [comment]
Hi,
Is this an issue with the Spotify web player specifically or with other web players such as Pandora?
If it's an issue with all the web players then the issue is that for the program to work it has to be set up in a specific way. 

To use the Web Players you need to do the following:

1. Open Essential Now Playing.
2. Select the Player and set the file path.
3. Head to the Spotify web player or any other web player.
4. Click on the Now Playing Companion Extension and "Use on this page".
(You should see the NativeMessagingInterface background process start up in Task Manager)
5. On the web pop-up click "Start".
6. Go back to Essential Now Playing app and hit "Start!".

The issue seems to be that you must have EssentialNowPlaying.exe running before you enable the Playing Companion Extension in order for the NativeMessagingInterface to load properly. NativeMessagingInterface.exe should start automatically.

After NativeMessagingInterface has been loaded you can go ahead and change WebApps (Spotify, SoundCloud, etc.) without any issues since the problem was initializing NativeMessagingInterface.

The readme will be updated with these steps for now but we'll be working towards fixing this and making it more user friendly.

If the issue is with the Spotify web player only then let us know and we'll see what the issue is.

**Comment by IranEG** [comment]
Hi,
Are you using the web player from play.spotify.com or is it embedded on another site? The spotify web player is only supported if it's in play.spotify.com for now. It will give a "Not supported" error if the url is different.

We have just found an issue with the Spotify web player but I don't know if it's related with your issue since it shouldn't give an "Not supported" error.

**Comment by lolcamp95** [comment]
The issue is only on the Spotify web player. But when I try to change URL to play.spotify.com, it autochanges it open.spotify.com
